- hosts: db

  name: Install and configure a database
  tasks:
    - name: Ensure firewall-cmd and firewall-cmd python packages are present
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - firewalld
        - python-firewalld

    - name: Install mariadb
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - mariadb
        - mariadb-server
        - MySQL-python
        - php-mysql

    - name: Open port
      firewalld:
        state: enabled
        zone: public
        immediate: yes
        service: mysql
        permanent: yes

    - name: Ensure MariaDB is properly configured
      template:
        src: ../templates/etc_my.cnf.d_network.cnf.j2
        dest: /etc/my.cnf.d/network.cnf
        backup: yes

    - name: start and enable mariadb
      service:
        name: mariadb
        enabled: yes
        state: started

    - name: Create the database
      mysql_db:
        name: '{{ dbname }}'
        encoding: utf8
        state: present

    - name: Create user and perms.
      mysql_user:
        name: '{{ dbuser }}'
        state: present
        host: '%'
        password: '{{ dbpass }}'
        priv: '*.*:ALL'
